# Generated by Django 4.2.4 on 2023-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zesty_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
