# Generated by Django 4.2.4 on 2023-08-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zesty_app', '0005_remove_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userNo',
            field=models.IntegerField(default=1),
        ),
    ]
