# Generated by Django 4.2.4 on 2023-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zesty_app', '0006_order_userno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('taste', 'Taste'), ('service', 'Service')], default='taste', max_length=10)),
                ('dishes', models.ManyToManyField(to='zesty_app.dish')),
            ],
        ),
    ]
